# Permalinks
permalink:           pretty

# Setup
title:               Yuanbiao Wang
tagline:             Undergraduates from THU
url:                 http://agil27.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Yuanbiao Wang
  url:               https://twitter.com/dashwooden
  email:             wangyuanbiao2016@gmail.com

# Custom vars
version:             2.0.1
github:
  repo:              https://github.com/jamigibbs/portfolio
google_analytics:    UA-3363703-15

# Gems
plugins:
  # - jekyll-paginate
  # - jekyll-gist
